language: python

python:
  - "2.7"

install:
  - pip install .

script:
  # pytests
  - python setup.py test
  # script docs
  - UniFastaFormat.py -h
  - faToTwoBit
  - mfe_index_db.py -h
  - MFE_primer.py -h