language: python

python:
  - "2.7"

install:
  - pip install .

script:
  # pytest
  - pytest
  # script docs
  - UniFastaFormat.py -h
  - mfe_index_db.py -h
  - MFE_primer.py -h
  # example
  - UniFastaFormat.py -i tests/data/test.rna
  - faToTwoBit tests/data/test.rna.unifasta tests/data/test.rna.2bit
  - mfe_index_db.py -f tests/data/test.rna.unifasta -k 9